### ISSUE TITLE
Uploader fails to read windows style path

### ISSUE THREAD

**Issue by krissrex** [krissrex/ScreenCapture-Plugins#1]
Paths in windows are separated with <code>\</code>. Jsch does not understand this, and paths need conversion.
The <code>\n</code> in \ntnu is printed as a newline, indicating that the code interprets the backslashes as escaping.
### Workaround

Use double slashes. <code>C:\\path\\to\\file</code>
Or use forward slashes. <code>C:/path/to/file</code>
### Reproduction

**Input:**
<code>privateKey=C:\Users\Jørgen\Desktop\ScreenCapture\ntnu_rsa</code>
**Error**
<code>com.jcraft.jsch.JSchException: java.io.FileNotFoundException: C:UsersJørgenDesktopScreenCapture
tnu_rsa</code>

**Side note:**
Full output indicates another bug in [ScreenCapture](https://github.com/krissrex/ScreenCapture/blob/master/ScreenCapture/src/com/polarbirds/screencapture/plugin/PluginHandler.java):
<code>Could not find plugin "ScreenCapture" in path "ï»¿#". Please verify url.</code>

``` java
Could not find plugin "ScreenCapture" in path "ï»¿#". Please verify url.
java.net.MalformedURLException: no protocol: ï»¿#
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at com.polarbirds.screencapture.plugin.PluginHandler.<init>(PluginHandler.java:25)
        at com.polarbirds.screencapture.Controller.loadPlugins(Controller.java:47)
        at com.polarbirds.screencapture.Controller.start(Controller.java:66)
        at com.polarbirds.screencapture.Main.main(Main.java:48)
Unknown exception occured while loading "com.polarbirds.screencapture.plugin.uploader.Uploader"
com.jcraft.jsch.JSchException: java.io.FileNotFoundException: C:UsersJørgenDesktopScreenCapture
tnu_rsa (The filename, directory name, or volume label syntax is incorrect)
        at com.jcraft.jsch.KeyPair.load(KeyPair.java:525)
        at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
        at com.jcraft.jsch.JSch.addIdentity(JSch.java:393)
        at com.jcraft.jsch.JSch.addIdentity(JSch.java:353)
        at com.polarbirds.screencapture.plugin.uploader.Uploader.<init>(Uploader.java:43)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at com.polarbirds.screencapture.plugin.PluginHandler.<init>(PluginHandler.java:28)
        at com.polarbirds.screencapture.Controller.loadPlugins(Controller.java:47)
        at com.polarbirds.screencapture.Controller.start(Controller.java:66)
        at com.polarbirds.screencapture.Main.main(Main.java:48)
Caused by: java.io.FileNotFoundException: C:UsersJørgenDesktopScreenCapture
tnu_rsa (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.jcraft.jsch.Util.fromFile(Util.java:508)
        at com.jcraft.jsch.KeyPair.load(KeyPair.java:522)
        ... 13 more
Loaded 0 plugins.
```

**Comment by trondhumbor** [comment]
I've updated the Uploader plugin. It now escapes Windows-paths automatically. You should now only use a single backslash, or forward slashes in paths.

Please submit a separate issue for the second issue mentioned in the original post.

**Comment by trondhumbor** [comment]
Due to a recent restructure of the configuration file, your paths now need to conform with the JSON standard, which means you need to escape the paths.
